trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd observatory
    npm install -g @angular/cli
    npm install
    ng build --prod
    dir
  displayName: 'npm install and build'

- script: |
    npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'o97'
    targetPath: 'dist'